variables:
  buildConfiguration: Release
  buildTag: $[ startsWith(variables['Build.SourceBranch'], 'refs/tags') ]
  buildNumber: $[ variables['Build.BuildNumber'] ]

trigger:
  tags:
    include:
    - '*'
  branches:
    include:
    - '*'

jobs:
- job: Windows_build
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'Discord.Net.sln'
      arguments: '-v minimal -c $(buildConfiguration) /p:BuildNumber=$(buildNumber) /p:IsTagBuild=$(buildTag)'

  - script: dotnet test "test/Discord.Net.Tests.Unit/Discord.Net.Tests.Unit.csproj" --no-restore --no-build -v minimal -c $(buildConfiguration) --logger trx
    displayName: Unit Tests

  - script: dotnet test "test/Discord.Net.Analyzers.Tests/Discord.Net.Analyzers.Tests.csproj" --no-restore --no-build -v minimal -c $(buildConfiguration) --logger trx
    displayName: Analyzer Tests



