variables:
  buildConfiguration: Release

trigger:
  tags:
    include:
    - '*'
  branches:
    include:
    - '*'

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      packageType: 'sdk'
      version: '3.x'
  - template: azure/build.yml

- job: Windows_build
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: azure/build.yml
