variables:
  buildConfiguration: Release
  buildTag: $[ startsWith(variables['Build.SourceBranch'], 'refs/tags') ]
  buildNumber: $[ variables['Build.BuildNumber'] ]

trigger:
  tags:
    include:
    - '*'
  branches:
    include:
    - '*'

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: azure/build.yml

- job: Windows_build
  pool:
    vmImage: 'windows-latest'
  condition: ne(variables['Build.SourceBranch'], 'refs/heads/dev')
  steps:
  - template: azure/build.yml



