variables:
  buildConfiguration: Release
  buildTag: $[ startsWith(variables['Build.SourceBranch'], 'refs/tags') ]
  buildNumber: $[ variables['Build.BuildNumber'] ]

trigger:
  tags:
    include:
    - '*'
  branches:
    include:
    - '*'

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk'
    inputs:
      packageType: 'sdk'
      version: '3.x'
  - template: azure/build.yml

- job: Windows_build
  pool:
    vmImage: 'windows-2019'
  condition: ne(variables['Build.SourceBranch'], 'refs/heads/dev')
  steps:
  - template: azure/build.yml

- job: Windows_deploy
  pool:
    vmImage: 'windows-2019'
  condition: |
      succeeded()
  steps:
  - template: azure/build.yml
  - template: azure/deploy.yml
